[tasks.setup]
run = "lefthook install"

[tasks.format]
run = "ruff format ."

[tasks.lint]
run = "ruff check ."

[tasks.act]
run = 'act pull_request --secret-file .env -e .github/act/pull_request.json -j checks'
