name: PR Checks

on:
  pull_request:
    types: [ opened, synchronize, edited, reopened ]
    branches: [ master ]

permissions:
  contents: read
  pull-requests: write

jobs:
  checks:
    name: PR Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to head SHA
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Setup mise toolchain
        uses: jdx/mise-action@v2
        with:
          install: true

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Validate PR title
        run: mise x cocogitto -- cog verify "${{ github.event.pull_request.title }}"

      - name: Lint
        run: mise run lint
